# Generated by Django 5.0.2 on 2024-02-28 05:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authapi", "0002_user_role"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="role",
        ),
    ]
