# Generated by Django 5.0.2 on 2024-02-28 08:19

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authapi", "0003_remove_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="check_in_date",
            field=models.DateField(
                validators=[
                    django.core.validators.MinValueValidator(
                        limit_value=datetime.date(2024, 2, 28)
                    )
                ]
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="check_out_date",
            field=models.DateField(
                validators=[
                    django.core.validators.MinValueValidator(
                        limit_value=datetime.date(2024, 2, 28)
                    )
                ]
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="is_available",
            field=models.BooleanField(default=True),
        ),
    ]
